# Generated by Django 5.1.6 on 2025-05-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersession',
            old_name='user_agent',
            new_name='session_data',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='cookies',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='id',
        ),
        migrations.AddField(
            model_name='usersession',
            name='session_id',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
